src/Entity/Report.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReportRepository")
 */
class Report
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="reports")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $edrpou;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Type(type="integer")
     */
    private $nreg;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $file;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank
     */
    private $public_dt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEdrpou(): ?string
    {
        return $this->edrpou;
    }

    public function setEdrpou(string $edrpou): self
    {
        $this->edrpou = $edrpou;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNreg(): ?int
    {
        return $this->nreg;
    }

    public function setNreg(int $nreg): self
    {
        $this->nreg = $nreg;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getPublicDt(): ?\DateTimeInterface
    {
        return $this->public_dt;
    }

    public function setPublicDt(\DateTimeInterface $public_dt): self
    {
        $this->public_dt = $public_dt;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Report;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="main")
     */
    public function index()
    {
        $entityManager = $this->getDoctrine()->getManager();
        $reports = $entityManager->getRepository(Report::class)->findAll();
        
        return $this->render('home/index.html.twig', [
            'controller_name' => 'Upload XML',
            'reports' => $reports,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ controller_name }}{% endblock %}

{% block body %}
   
<div class="row">
    <h1>{{ controller_name }}</h1>   
</div>

{% for label, messages in app.flashes %}
    <div class="row flash-notice">
    {% for message in messages %}  
        <div class="alert alert-secondary" role="alert">
            {{ message }}    
        </div>
    {% endfor %}
    </div>
{% endfor %}  

<div class="row">
    <a href="{{ path('upload_form') }}" class="btn btn-primary">Upload report</a>    
</div>    

<div class="row">
<h3>Поданные отчеты</h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Пользователь</th>
      <th scope="col">Код предприятия</th>
      <th scope="col">Наименование предприятия</th>
      <th scope="col">Тип информации</th>
      <th scope="col">Дата размещения</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
{% for report in reports %}
    <tr>
      <td>{{ report.user.email }}</td>
      <td>{{ report.edrpou }}</td>
      <td>{{ report.name }}</td>
      <td>{{ report.nreg }}</td>
      <td>{{ report.publicDt|date('Y-m-d') }}</td>
      <td><a href="" class="btn">Переглянути</a> </td>
    </tr>
{% endfor %}     
  </tbody>
</table>

</div>
    
    
{% endblock %}